import { render } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import {
  ActivityIcon,
  AlertCircleIcon,
  AlertOctagonIcon,
  AlertTriangleIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  BarChart3Icon,
  BellIcon,
  BookOpenIcon,
  BoxIcon,
  Building2Icon,
  CalendarClockIcon,
  CalendarDaysIcon,
  CalendarIcon,
  CheckCheckIcon,
  CheckCircle2Icon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleDollarSignIcon,
  CircleSlashIcon,
  ClipboardCheckIcon,
  ClipboardListIcon,
  ClockIcon,
  CoffeeIcon,
  CoinsIcon,
  CrownIcon,
  DownloadIcon,
  DumbbellIcon,
  EyeIcon,
  EyeOffIcon,
  FlameIcon,
  FolderOpenIcon,
  GemIcon,
  GiftIcon,
  GraduationCapIcon,
  HandshakeIcon,
  HistoryIcon,
  HomeIcon,
  type IconComponentType,
  InfoIcon,
  LayoutDashboardIcon,
  ListChecksIcon,
  Loader2Icon,
  LockIcon,
  LogOutIcon,
  MapPinIcon,
  MegaphoneIcon,
  MessageCircleIcon,
  MoonIcon,
  OctagonXIcon,
  PartyPopperIcon,
  PencilIcon,
  PercentIcon,
  PhoneCallIcon,
  PhoneIcon,
  PlusIcon,
  RadioIcon,
  RefreshCcwIcon,
  SaveIcon,
  SearchIcon,
  SendIcon,
  SettingsIcon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  SmartphoneIcon,
  SparklesIcon,
  StarIcon,
  SunIcon,
  SunriseIcon,
  SwordIcon,
  SwordsIcon,
  TargetIcon,
  TheaterIcon,
  Trash2Icon,
  TrendingUpIcon,
  TrophyIcon,
  UploadIcon,
  UserCheckIcon,
  UserRoundIcon,
  UsersIcon,
  XIcon,
  ZapIcon,
} from "./icons";

const icons: [string, IconComponentType][] = [
  ["ActivityIcon", ActivityIcon],
  ["AlertCircleIcon", AlertCircleIcon],
  ["AlertOctagonIcon", AlertOctagonIcon],
  ["AlertTriangleIcon", AlertTriangleIcon],
  ["ArrowLeftIcon", ArrowLeftIcon],
  ["ArrowRightIcon", ArrowRightIcon],
  ["BarChart3Icon", BarChart3Icon],
  ["BellIcon", BellIcon],
  ["BookOpenIcon", BookOpenIcon],
  ["BoxIcon", BoxIcon],
  ["Building2Icon", Building2Icon],
  ["CalendarIcon", CalendarIcon],
  ["CalendarClockIcon", CalendarClockIcon],
  ["CalendarDaysIcon", CalendarDaysIcon],
  ["CheckIcon", CheckIcon],
  ["CheckCheckIcon", CheckCheckIcon],
  ["CheckCircle2Icon", CheckCircle2Icon],
  ["ChevronDownIcon", ChevronDownIcon],
  ["ChevronLeftIcon", ChevronLeftIcon],
  ["ChevronRightIcon", ChevronRightIcon],
  ["ChevronUpIcon", ChevronUpIcon],
  ["CircleDollarSignIcon", CircleDollarSignIcon],
  ["CircleSlashIcon", CircleSlashIcon],
  ["ClipboardCheckIcon", ClipboardCheckIcon],
  ["ClipboardListIcon", ClipboardListIcon],
  ["ClockIcon", ClockIcon],
  ["CoffeeIcon", CoffeeIcon],
  ["CoinsIcon", CoinsIcon],
  ["CrownIcon", CrownIcon],
  ["DownloadIcon", DownloadIcon],
  ["DumbbellIcon", DumbbellIcon],
  ["EyeIcon", EyeIcon],
  ["EyeOffIcon", EyeOffIcon],
  ["FlameIcon", FlameIcon],
  ["FolderOpenIcon", FolderOpenIcon],
  ["GemIcon", GemIcon],
  ["GiftIcon", GiftIcon],
  ["GraduationCapIcon", GraduationCapIcon],
  ["HandshakeIcon", HandshakeIcon],
  ["HistoryIcon", HistoryIcon],
  ["HomeIcon", HomeIcon],
  ["InfoIcon", InfoIcon],
  ["LayoutDashboardIcon", LayoutDashboardIcon],
  ["ListChecksIcon", ListChecksIcon],
  ["Loader2Icon", Loader2Icon],
  ["LockIcon", LockIcon],
  ["LogOutIcon", LogOutIcon],
  ["MapPinIcon", MapPinIcon],
  ["MegaphoneIcon", MegaphoneIcon],
  ["MessageCircleIcon", MessageCircleIcon],
  ["MoonIcon", MoonIcon],
  ["OctagonXIcon", OctagonXIcon],
  ["PartyPopperIcon", PartyPopperIcon],
  ["PencilIcon", PencilIcon],
  ["PercentIcon", PercentIcon],
  ["PhoneIcon", PhoneIcon],
  ["PhoneCallIcon", PhoneCallIcon],
  ["PlusIcon", PlusIcon],
  ["RadioIcon", RadioIcon],
  ["RefreshCcwIcon", RefreshCcwIcon],
  ["SaveIcon", SaveIcon],
  ["SearchIcon", SearchIcon],
  ["SendIcon", SendIcon],
  ["SettingsIcon", SettingsIcon],
  ["ShieldAlertIcon", ShieldAlertIcon],
  ["ShieldCheckIcon", ShieldCheckIcon],
  ["SmartphoneIcon", SmartphoneIcon],
  ["SparklesIcon", SparklesIcon],
  ["StarIcon", StarIcon],
  ["SunIcon", SunIcon],
  ["SunriseIcon", SunriseIcon],
  ["SwordIcon", SwordIcon],
  ["SwordsIcon", SwordsIcon],
  ["TargetIcon", TargetIcon],
  ["TheaterIcon", TheaterIcon],
  ["Trash2Icon", Trash2Icon],
  ["TrendingUpIcon", TrendingUpIcon],
  ["TrophyIcon", TrophyIcon],
  ["UploadIcon", UploadIcon],
  ["UserCheckIcon", UserCheckIcon],
  ["UserRoundIcon", UserRoundIcon],
  ["UsersIcon", UsersIcon],
  ["XIcon", XIcon],
  ["ZapIcon", ZapIcon],
];

describe("icons", () => {
  it(`exports 84 icons`, () => {
    expect(icons).toHaveLength(84);
  });

  it.each(icons)("%s renders an svg", (_name, Icon) => {
    const { container } = render(<Icon data-testid="icon" />);
    expect(container.querySelector("svg")).not.toBeNull();
  });
});
